//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.8.3928.0。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="OCVWebServiceSoap", Namespace="http://tempuri.org/")]
public partial class OCVWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback ConnectTestOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateOCVStatusOperationCompleted;
    
    private System.Threading.SendOrPostCallback getTechnologyInfoByBarCodeOperationCompleted;
    
    private System.Threading.SendOrPostCallback getTrayTpyeOperationCompleted;
    
    private System.Threading.SendOrPostCallback getOCVTestResultByBarCodeOperationCompleted;
    
    private System.Threading.SendOrPostCallback RequestOutFeedOperationCompleted;
    
    /// <remarks/>
    public OCVWebService() {
        this.Url = "http://172.22.20.16:9006/OCVWebService.asmx";
    }
    
    /// <remarks/>
    public event ConnectTestCompletedEventHandler ConnectTestCompleted;
    
    /// <remarks/>
    public event UpdateOCVStatusCompletedEventHandler UpdateOCVStatusCompleted;
    
    /// <remarks/>
    public event getTechnologyInfoByBarCodeCompletedEventHandler getTechnologyInfoByBarCodeCompleted;
    
    /// <remarks/>
    public event getTrayTpyeCompletedEventHandler getTrayTpyeCompleted;
    
    /// <remarks/>
    public event getOCVTestResultByBarCodeCompletedEventHandler getOCVTestResultByBarCodeCompleted;
    
    /// <remarks/>
    public event RequestOutFeedCompletedEventHandler RequestOutFeedCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConnectTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string ConnectTest() {
        object[] results = this.Invoke("ConnectTest", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginConnectTest(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ConnectTest", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndConnectTest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ConnectTestAsync() {
        this.ConnectTestAsync(null);
    }
    
    /// <remarks/>
    public void ConnectTestAsync(object userState) {
        if ((this.ConnectTestOperationCompleted == null)) {
            this.ConnectTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConnectTestOperationCompleted);
        }
        this.InvokeAsync("ConnectTest", new object[0], this.ConnectTestOperationCompleted, userState);
    }
    
    private void OnConnectTestOperationCompleted(object arg) {
        if ((this.ConnectTestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ConnectTestCompleted(this, new ConnectTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOCVStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Status UpdateOCVStatus(string EquipNum, int WorkMode, int Status, string ErrorMsg) {
        object[] results = this.Invoke("UpdateOCVStatus", new object[] {
                    EquipNum,
                    WorkMode,
                    Status,
                    ErrorMsg});
        return ((Status)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateOCVStatus(string EquipNum, int WorkMode, int Status, string ErrorMsg, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateOCVStatus", new object[] {
                    EquipNum,
                    WorkMode,
                    Status,
                    ErrorMsg}, callback, asyncState);
    }
    
    /// <remarks/>
    public Status EndUpdateOCVStatus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Status)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateOCVStatusAsync(string EquipNum, int WorkMode, int Status, string ErrorMsg) {
        this.UpdateOCVStatusAsync(EquipNum, WorkMode, Status, ErrorMsg, null);
    }
    
    /// <remarks/>
    public void UpdateOCVStatusAsync(string EquipNum, int WorkMode, int Status, string ErrorMsg, object userState) {
        if ((this.UpdateOCVStatusOperationCompleted == null)) {
            this.UpdateOCVStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOCVStatusOperationCompleted);
        }
        this.InvokeAsync("UpdateOCVStatus", new object[] {
                    EquipNum,
                    WorkMode,
                    Status,
                    ErrorMsg}, this.UpdateOCVStatusOperationCompleted, userState);
    }
    
    private void OnUpdateOCVStatusOperationCompleted(object arg) {
        if ((this.UpdateOCVStatusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateOCVStatusCompleted(this, new UpdateOCVStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTechnologyInfoByBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public TrayInfoOCV getTechnologyInfoByBarCode(string EquipNum, string BarCode) {
        object[] results = this.Invoke("getTechnologyInfoByBarCode", new object[] {
                    EquipNum,
                    BarCode});
        return ((TrayInfoOCV)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTechnologyInfoByBarCode(string EquipNum, string BarCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTechnologyInfoByBarCode", new object[] {
                    EquipNum,
                    BarCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public TrayInfoOCV EndgetTechnologyInfoByBarCode(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((TrayInfoOCV)(results[0]));
    }
    
    /// <remarks/>
    public void getTechnologyInfoByBarCodeAsync(string EquipNum, string BarCode) {
        this.getTechnologyInfoByBarCodeAsync(EquipNum, BarCode, null);
    }
    
    /// <remarks/>
    public void getTechnologyInfoByBarCodeAsync(string EquipNum, string BarCode, object userState) {
        if ((this.getTechnologyInfoByBarCodeOperationCompleted == null)) {
            this.getTechnologyInfoByBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTechnologyInfoByBarCodeOperationCompleted);
        }
        this.InvokeAsync("getTechnologyInfoByBarCode", new object[] {
                    EquipNum,
                    BarCode}, this.getTechnologyInfoByBarCodeOperationCompleted, userState);
    }
    
    private void OngetTechnologyInfoByBarCodeOperationCompleted(object arg) {
        if ((this.getTechnologyInfoByBarCodeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getTechnologyInfoByBarCodeCompleted(this, new getTechnologyInfoByBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTrayTpye", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public TrayTypeOCV getTrayTpye(string EquipNum, string BarCode) {
        object[] results = this.Invoke("getTrayTpye", new object[] {
                    EquipNum,
                    BarCode});
        return ((TrayTypeOCV)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTrayTpye(string EquipNum, string BarCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTrayTpye", new object[] {
                    EquipNum,
                    BarCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public TrayTypeOCV EndgetTrayTpye(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((TrayTypeOCV)(results[0]));
    }
    
    /// <remarks/>
    public void getTrayTpyeAsync(string EquipNum, string BarCode) {
        this.getTrayTpyeAsync(EquipNum, BarCode, null);
    }
    
    /// <remarks/>
    public void getTrayTpyeAsync(string EquipNum, string BarCode, object userState) {
        if ((this.getTrayTpyeOperationCompleted == null)) {
            this.getTrayTpyeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTrayTpyeOperationCompleted);
        }
        this.InvokeAsync("getTrayTpye", new object[] {
                    EquipNum,
                    BarCode}, this.getTrayTpyeOperationCompleted, userState);
    }
    
    private void OngetTrayTpyeOperationCompleted(object arg) {
        if ((this.getTrayTpyeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getTrayTpyeCompleted(this, new getTrayTpyeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOCVTestResultByBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Result getOCVTestResultByBarCode(string EquipNum, string BarCode, BatteryInfo[] lstBattery) {
        object[] results = this.Invoke("getOCVTestResultByBarCode", new object[] {
                    EquipNum,
                    BarCode,
                    lstBattery});
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetOCVTestResultByBarCode(string EquipNum, string BarCode, BatteryInfo[] lstBattery, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getOCVTestResultByBarCode", new object[] {
                    EquipNum,
                    BarCode,
                    lstBattery}, callback, asyncState);
    }
    
    /// <remarks/>
    public Result EndgetOCVTestResultByBarCode(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public void getOCVTestResultByBarCodeAsync(string EquipNum, string BarCode, BatteryInfo[] lstBattery) {
        this.getOCVTestResultByBarCodeAsync(EquipNum, BarCode, lstBattery, null);
    }
    
    /// <remarks/>
    public void getOCVTestResultByBarCodeAsync(string EquipNum, string BarCode, BatteryInfo[] lstBattery, object userState) {
        if ((this.getOCVTestResultByBarCodeOperationCompleted == null)) {
            this.getOCVTestResultByBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOCVTestResultByBarCodeOperationCompleted);
        }
        this.InvokeAsync("getOCVTestResultByBarCode", new object[] {
                    EquipNum,
                    BarCode,
                    lstBattery}, this.getOCVTestResultByBarCodeOperationCompleted, userState);
    }
    
    private void OngetOCVTestResultByBarCodeOperationCompleted(object arg) {
        if ((this.getOCVTestResultByBarCodeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getOCVTestResultByBarCodeCompleted(this, new getOCVTestResultByBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestOutFeed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Result RequestOutFeed(string EquipNum, string BarCode, string Status) {
        object[] results = this.Invoke("RequestOutFeed", new object[] {
                    EquipNum,
                    BarCode,
                    Status});
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRequestOutFeed(string EquipNum, string BarCode, string Status, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RequestOutFeed", new object[] {
                    EquipNum,
                    BarCode,
                    Status}, callback, asyncState);
    }
    
    /// <remarks/>
    public Result EndRequestOutFeed(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public void RequestOutFeedAsync(string EquipNum, string BarCode, string Status) {
        this.RequestOutFeedAsync(EquipNum, BarCode, Status, null);
    }
    
    /// <remarks/>
    public void RequestOutFeedAsync(string EquipNum, string BarCode, string Status, object userState) {
        if ((this.RequestOutFeedOperationCompleted == null)) {
            this.RequestOutFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestOutFeedOperationCompleted);
        }
        this.InvokeAsync("RequestOutFeed", new object[] {
                    EquipNum,
                    BarCode,
                    Status}, this.RequestOutFeedOperationCompleted, userState);
    }
    
    private void OnRequestOutFeedOperationCompleted(object arg) {
        if ((this.RequestOutFeedCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RequestOutFeedCompleted(this, new RequestOutFeedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Status {
    
    private int codeField;
    
    private string messageField;
    
    /// <remarks/>
    public int Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Result {
    
    private int codeField;
    
    private string msgField;
    
    /// <remarks/>
    public int Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Msg {
        get {
            return this.msgField;
        }
        set {
            this.msgField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class BatteryInfo {
    
    private int positionField;
    
    private string batteryCodeField;
    
    private int resultField;
    
    /// <remarks/>
    public int Position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public string BatteryCode {
        get {
            return this.batteryCodeField;
        }
        set {
            this.batteryCodeField = value;
        }
    }
    
    /// <remarks/>
    public int Result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class TrayTypeOCV {
    
    private string trayTypeField;
    
    private Status statusField;
    
    /// <remarks/>
    public string TrayType {
        get {
            return this.trayTypeField;
        }
        set {
            this.trayTypeField = value;
        }
    }
    
    /// <remarks/>
    public Status Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class TrayInfoResult {
    
    private int positionField;
    
    private string batteryCodeField;
    
    /// <remarks/>
    public int Position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public string BatteryCode {
        get {
            return this.batteryCodeField;
        }
        set {
            this.batteryCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class TrayInfoOCV {
    
    private string equipNumField;
    
    private string trayCodeField;
    
    private int oprationTypeField;
    
    private string oprationVersionField;
    
    private string temperatureField;
    
    private TrayInfoResult[] trayInfoLstResultField;
    
    private Status statusField;
    
    private string operationField;
    
    /// <remarks/>
    public string EquipNum {
        get {
            return this.equipNumField;
        }
        set {
            this.equipNumField = value;
        }
    }
    
    /// <remarks/>
    public string trayCode {
        get {
            return this.trayCodeField;
        }
        set {
            this.trayCodeField = value;
        }
    }
    
    /// <remarks/>
    public int oprationType {
        get {
            return this.oprationTypeField;
        }
        set {
            this.oprationTypeField = value;
        }
    }
    
    /// <remarks/>
    public string oprationVersion {
        get {
            return this.oprationVersionField;
        }
        set {
            this.oprationVersionField = value;
        }
    }
    
    /// <remarks/>
    public string temperature {
        get {
            return this.temperatureField;
        }
        set {
            this.temperatureField = value;
        }
    }
    
    /// <remarks/>
    public TrayInfoResult[] TrayInfoLstResult {
        get {
            return this.trayInfoLstResultField;
        }
        set {
            this.trayInfoLstResultField = value;
        }
    }
    
    /// <remarks/>
    public Status Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string Operation {
        get {
            return this.operationField;
        }
        set {
            this.operationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void ConnectTestCompletedEventHandler(object sender, ConnectTestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ConnectTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ConnectTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void UpdateOCVStatusCompletedEventHandler(object sender, UpdateOCVStatusCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateOCVStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateOCVStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Status Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Status)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void getTechnologyInfoByBarCodeCompletedEventHandler(object sender, getTechnologyInfoByBarCodeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getTechnologyInfoByBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getTechnologyInfoByBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public TrayInfoOCV Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((TrayInfoOCV)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void getTrayTpyeCompletedEventHandler(object sender, getTrayTpyeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getTrayTpyeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getTrayTpyeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public TrayTypeOCV Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((TrayTypeOCV)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void getOCVTestResultByBarCodeCompletedEventHandler(object sender, getOCVTestResultByBarCodeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getOCVTestResultByBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getOCVTestResultByBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Result Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Result)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void RequestOutFeedCompletedEventHandler(object sender, RequestOutFeedCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RequestOutFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RequestOutFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Result Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Result)(this.results[0]));
        }
    }
}
