//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WmsWebService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://tempuri.org/")]
    public partial class Status : object
    {
        
        private int CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrayInfoOCV", Namespace="http://tempuri.org/")]
    public partial class TrayInfoOCV : object
    {
        
        private string EquipNumField;
        
        private string trayCodeField;
        
        private int oprationTypeField;
        
        private string oprationVersionField;
        
        private string temperatureField;
        
        private WmsWebService.TrayInfoResult[] TrayInfoLstResultField;
        
        private WmsWebService.Status StatusField;
        
        private string OperationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EquipNum
        {
            get
            {
                return this.EquipNumField;
            }
            set
            {
                this.EquipNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string trayCode
        {
            get
            {
                return this.trayCodeField;
            }
            set
            {
                this.trayCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int oprationType
        {
            get
            {
                return this.oprationTypeField;
            }
            set
            {
                this.oprationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string oprationVersion
        {
            get
            {
                return this.oprationVersionField;
            }
            set
            {
                this.oprationVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string temperature
        {
            get
            {
                return this.temperatureField;
            }
            set
            {
                this.temperatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WmsWebService.TrayInfoResult[] TrayInfoLstResult
        {
            get
            {
                return this.TrayInfoLstResultField;
            }
            set
            {
                this.TrayInfoLstResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WmsWebService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Operation
        {
            get
            {
                return this.OperationField;
            }
            set
            {
                this.OperationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrayInfoResult", Namespace="http://tempuri.org/")]
    public partial class TrayInfoResult : object
    {
        
        private int PositionField;
        
        private string BatteryCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BatteryCode
        {
            get
            {
                return this.BatteryCodeField;
            }
            set
            {
                this.BatteryCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrayTypeOCV", Namespace="http://tempuri.org/")]
    public partial class TrayTypeOCV : object
    {
        
        private string TrayTypeField;
        
        private WmsWebService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TrayType
        {
            get
            {
                return this.TrayTypeField;
            }
            set
            {
                this.TrayTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WmsWebService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatteryInfo", Namespace="http://tempuri.org/")]
    public partial class BatteryInfo : object
    {
        
        private int PositionField;
        
        private string BatteryCodeField;
        
        private int ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BatteryCode
        {
            get
            {
                return this.BatteryCodeField;
            }
            set
            {
                this.BatteryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://tempuri.org/")]
    public partial class Result : object
    {
        
        private int CodeField;
        
        private string MsgField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Msg
        {
            get
            {
                return this.MsgField;
            }
            set
            {
                this.MsgField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WmsWebService.OCVWebServiceSoap")]
    public interface OCVWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConnectTest", ReplyAction="*")]
        System.Threading.Tasks.Task<WmsWebService.ConnectTestResponse> ConnectTestAsync(WmsWebService.ConnectTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOCVStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WmsWebService.UpdateOCVStatusResponse> UpdateOCVStatusAsync(WmsWebService.UpdateOCVStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTechnologyInfoByBarCode", ReplyAction="*")]
        System.Threading.Tasks.Task<WmsWebService.getTechnologyInfoByBarCodeResponse> getTechnologyInfoByBarCodeAsync(WmsWebService.getTechnologyInfoByBarCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTrayTpye", ReplyAction="*")]
        System.Threading.Tasks.Task<WmsWebService.getTrayTpyeResponse> getTrayTpyeAsync(WmsWebService.getTrayTpyeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOCVTestResultByBarCode", ReplyAction="*")]
        System.Threading.Tasks.Task<WmsWebService.getOCVTestResultByBarCodeResponse> getOCVTestResultByBarCodeAsync(WmsWebService.getOCVTestResultByBarCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestOutFeed", ReplyAction="*")]
        System.Threading.Tasks.Task<WmsWebService.RequestOutFeedResponse> RequestOutFeedAsync(WmsWebService.RequestOutFeedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConnectTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConnectTest", Namespace="http://tempuri.org/", Order=0)]
        public WmsWebService.ConnectTestRequestBody Body;
        
        public ConnectTestRequest()
        {
        }
        
        public ConnectTestRequest(WmsWebService.ConnectTestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConnectTestRequestBody
    {
        
        public ConnectTestRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConnectTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConnectTestResponse", Namespace="http://tempuri.org/", Order=0)]
        public WmsWebService.ConnectTestResponseBody Body;
        
        public ConnectTestResponse()
        {
        }
        
        public ConnectTestResponse(WmsWebService.ConnectTestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConnectTestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConnectTestResult;
        
        public ConnectTestResponseBody()
        {
        }
        
        public ConnectTestResponseBody(string ConnectTestResult)
        {
            this.ConnectTestResult = ConnectTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOCVStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOCVStatus", Namespace="http://tempuri.org/", Order=0)]
        public WmsWebService.UpdateOCVStatusRequestBody Body;
        
        public UpdateOCVStatusRequest()
        {
        }
        
        public UpdateOCVStatusRequest(WmsWebService.UpdateOCVStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOCVStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EquipNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int WorkMode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ErrorMsg;
        
        public UpdateOCVStatusRequestBody()
        {
        }
        
        public UpdateOCVStatusRequestBody(string EquipNum, int WorkMode, int Status, string ErrorMsg)
        {
            this.EquipNum = EquipNum;
            this.WorkMode = WorkMode;
            this.Status = Status;
            this.ErrorMsg = ErrorMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOCVStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOCVStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public WmsWebService.UpdateOCVStatusResponseBody Body;
        
        public UpdateOCVStatusResponse()
        {
        }
        
        public UpdateOCVStatusResponse(WmsWebService.UpdateOCVStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOCVStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WmsWebService.Status UpdateOCVStatusResult;
        
        public UpdateOCVStatusResponseBody()
        {
        }
        
        public UpdateOCVStatusResponseBody(WmsWebService.Status UpdateOCVStatusResult)
        {
            this.UpdateOCVStatusResult = UpdateOCVStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTechnologyInfoByBarCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTechnologyInfoByBarCode", Namespace="http://tempuri.org/", Order=0)]
        public WmsWebService.getTechnologyInfoByBarCodeRequestBody Body;
        
        public getTechnologyInfoByBarCodeRequest()
        {
        }
        
        public getTechnologyInfoByBarCodeRequest(WmsWebService.getTechnologyInfoByBarCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTechnologyInfoByBarCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EquipNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BarCode;
        
        public getTechnologyInfoByBarCodeRequestBody()
        {
        }
        
        public getTechnologyInfoByBarCodeRequestBody(string EquipNum, string BarCode)
        {
            this.EquipNum = EquipNum;
            this.BarCode = BarCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTechnologyInfoByBarCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTechnologyInfoByBarCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WmsWebService.getTechnologyInfoByBarCodeResponseBody Body;
        
        public getTechnologyInfoByBarCodeResponse()
        {
        }
        
        public getTechnologyInfoByBarCodeResponse(WmsWebService.getTechnologyInfoByBarCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTechnologyInfoByBarCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WmsWebService.TrayInfoOCV getTechnologyInfoByBarCodeResult;
        
        public getTechnologyInfoByBarCodeResponseBody()
        {
        }
        
        public getTechnologyInfoByBarCodeResponseBody(WmsWebService.TrayInfoOCV getTechnologyInfoByBarCodeResult)
        {
            this.getTechnologyInfoByBarCodeResult = getTechnologyInfoByBarCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTrayTpyeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTrayTpye", Namespace="http://tempuri.org/", Order=0)]
        public WmsWebService.getTrayTpyeRequestBody Body;
        
        public getTrayTpyeRequest()
        {
        }
        
        public getTrayTpyeRequest(WmsWebService.getTrayTpyeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTrayTpyeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EquipNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BarCode;
        
        public getTrayTpyeRequestBody()
        {
        }
        
        public getTrayTpyeRequestBody(string EquipNum, string BarCode)
        {
            this.EquipNum = EquipNum;
            this.BarCode = BarCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTrayTpyeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTrayTpyeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WmsWebService.getTrayTpyeResponseBody Body;
        
        public getTrayTpyeResponse()
        {
        }
        
        public getTrayTpyeResponse(WmsWebService.getTrayTpyeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTrayTpyeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WmsWebService.TrayTypeOCV getTrayTpyeResult;
        
        public getTrayTpyeResponseBody()
        {
        }
        
        public getTrayTpyeResponseBody(WmsWebService.TrayTypeOCV getTrayTpyeResult)
        {
            this.getTrayTpyeResult = getTrayTpyeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOCVTestResultByBarCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOCVTestResultByBarCode", Namespace="http://tempuri.org/", Order=0)]
        public WmsWebService.getOCVTestResultByBarCodeRequestBody Body;
        
        public getOCVTestResultByBarCodeRequest()
        {
        }
        
        public getOCVTestResultByBarCodeRequest(WmsWebService.getOCVTestResultByBarCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getOCVTestResultByBarCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EquipNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BarCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WmsWebService.BatteryInfo[] lstBattery;
        
        public getOCVTestResultByBarCodeRequestBody()
        {
        }
        
        public getOCVTestResultByBarCodeRequestBody(string EquipNum, string BarCode, WmsWebService.BatteryInfo[] lstBattery)
        {
            this.EquipNum = EquipNum;
            this.BarCode = BarCode;
            this.lstBattery = lstBattery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOCVTestResultByBarCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOCVTestResultByBarCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WmsWebService.getOCVTestResultByBarCodeResponseBody Body;
        
        public getOCVTestResultByBarCodeResponse()
        {
        }
        
        public getOCVTestResultByBarCodeResponse(WmsWebService.getOCVTestResultByBarCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getOCVTestResultByBarCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WmsWebService.Result getOCVTestResultByBarCodeResult;
        
        public getOCVTestResultByBarCodeResponseBody()
        {
        }
        
        public getOCVTestResultByBarCodeResponseBody(WmsWebService.Result getOCVTestResultByBarCodeResult)
        {
            this.getOCVTestResultByBarCodeResult = getOCVTestResultByBarCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOutFeedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOutFeed", Namespace="http://tempuri.org/", Order=0)]
        public WmsWebService.RequestOutFeedRequestBody Body;
        
        public RequestOutFeedRequest()
        {
        }
        
        public RequestOutFeedRequest(WmsWebService.RequestOutFeedRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestOutFeedRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EquipNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BarCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Status;
        
        public RequestOutFeedRequestBody()
        {
        }
        
        public RequestOutFeedRequestBody(string EquipNum, string BarCode, string Status)
        {
            this.EquipNum = EquipNum;
            this.BarCode = BarCode;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOutFeedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOutFeedResponse", Namespace="http://tempuri.org/", Order=0)]
        public WmsWebService.RequestOutFeedResponseBody Body;
        
        public RequestOutFeedResponse()
        {
        }
        
        public RequestOutFeedResponse(WmsWebService.RequestOutFeedResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestOutFeedResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WmsWebService.Result RequestOutFeedResult;
        
        public RequestOutFeedResponseBody()
        {
        }
        
        public RequestOutFeedResponseBody(WmsWebService.Result RequestOutFeedResult)
        {
            this.RequestOutFeedResult = RequestOutFeedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface OCVWebServiceSoapChannel : WmsWebService.OCVWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class OCVWebServiceSoapClient : System.ServiceModel.ClientBase<WmsWebService.OCVWebServiceSoap>, WmsWebService.OCVWebServiceSoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OCVWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(OCVWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), OCVWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OCVWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OCVWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OCVWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OCVWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OCVWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WmsWebService.ConnectTestResponse> WmsWebService.OCVWebServiceSoap.ConnectTestAsync(WmsWebService.ConnectTestRequest request)
        {
            return base.Channel.ConnectTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<WmsWebService.ConnectTestResponse> ConnectTestAsync()
        {
            WmsWebService.ConnectTestRequest inValue = new WmsWebService.ConnectTestRequest();
            inValue.Body = new WmsWebService.ConnectTestRequestBody();
            return ((WmsWebService.OCVWebServiceSoap)(this)).ConnectTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WmsWebService.UpdateOCVStatusResponse> WmsWebService.OCVWebServiceSoap.UpdateOCVStatusAsync(WmsWebService.UpdateOCVStatusRequest request)
        {
            return base.Channel.UpdateOCVStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WmsWebService.UpdateOCVStatusResponse> UpdateOCVStatusAsync(string EquipNum, int WorkMode, int Status, string ErrorMsg)
        {
            WmsWebService.UpdateOCVStatusRequest inValue = new WmsWebService.UpdateOCVStatusRequest();
            inValue.Body = new WmsWebService.UpdateOCVStatusRequestBody();
            inValue.Body.EquipNum = EquipNum;
            inValue.Body.WorkMode = WorkMode;
            inValue.Body.Status = Status;
            inValue.Body.ErrorMsg = ErrorMsg;
            return ((WmsWebService.OCVWebServiceSoap)(this)).UpdateOCVStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WmsWebService.getTechnologyInfoByBarCodeResponse> WmsWebService.OCVWebServiceSoap.getTechnologyInfoByBarCodeAsync(WmsWebService.getTechnologyInfoByBarCodeRequest request)
        {
            return base.Channel.getTechnologyInfoByBarCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WmsWebService.getTechnologyInfoByBarCodeResponse> getTechnologyInfoByBarCodeAsync(string EquipNum, string BarCode)
        {
            WmsWebService.getTechnologyInfoByBarCodeRequest inValue = new WmsWebService.getTechnologyInfoByBarCodeRequest();
            inValue.Body = new WmsWebService.getTechnologyInfoByBarCodeRequestBody();
            inValue.Body.EquipNum = EquipNum;
            inValue.Body.BarCode = BarCode;
            return ((WmsWebService.OCVWebServiceSoap)(this)).getTechnologyInfoByBarCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WmsWebService.getTrayTpyeResponse> WmsWebService.OCVWebServiceSoap.getTrayTpyeAsync(WmsWebService.getTrayTpyeRequest request)
        {
            return base.Channel.getTrayTpyeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WmsWebService.getTrayTpyeResponse> getTrayTpyeAsync(string EquipNum, string BarCode)
        {
            WmsWebService.getTrayTpyeRequest inValue = new WmsWebService.getTrayTpyeRequest();
            inValue.Body = new WmsWebService.getTrayTpyeRequestBody();
            inValue.Body.EquipNum = EquipNum;
            inValue.Body.BarCode = BarCode;
            return ((WmsWebService.OCVWebServiceSoap)(this)).getTrayTpyeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WmsWebService.getOCVTestResultByBarCodeResponse> WmsWebService.OCVWebServiceSoap.getOCVTestResultByBarCodeAsync(WmsWebService.getOCVTestResultByBarCodeRequest request)
        {
            return base.Channel.getOCVTestResultByBarCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WmsWebService.getOCVTestResultByBarCodeResponse> getOCVTestResultByBarCodeAsync(string EquipNum, string BarCode, WmsWebService.BatteryInfo[] lstBattery)
        {
            WmsWebService.getOCVTestResultByBarCodeRequest inValue = new WmsWebService.getOCVTestResultByBarCodeRequest();
            inValue.Body = new WmsWebService.getOCVTestResultByBarCodeRequestBody();
            inValue.Body.EquipNum = EquipNum;
            inValue.Body.BarCode = BarCode;
            inValue.Body.lstBattery = lstBattery;
            return ((WmsWebService.OCVWebServiceSoap)(this)).getOCVTestResultByBarCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WmsWebService.RequestOutFeedResponse> WmsWebService.OCVWebServiceSoap.RequestOutFeedAsync(WmsWebService.RequestOutFeedRequest request)
        {
            return base.Channel.RequestOutFeedAsync(request);
        }
        
        public System.Threading.Tasks.Task<WmsWebService.RequestOutFeedResponse> RequestOutFeedAsync(string EquipNum, string BarCode, string Status)
        {
            WmsWebService.RequestOutFeedRequest inValue = new WmsWebService.RequestOutFeedRequest();
            inValue.Body = new WmsWebService.RequestOutFeedRequestBody();
            inValue.Body.EquipNum = EquipNum;
            inValue.Body.BarCode = BarCode;
            inValue.Body.Status = Status;
            return ((WmsWebService.OCVWebServiceSoap)(this)).RequestOutFeedAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OCVWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.OCVWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OCVWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://172.22.20.16:9006/OCVWebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.OCVWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://172.22.20.16:9006/OCVWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            OCVWebServiceSoap,
            
            OCVWebServiceSoap12,
        }
    }
}
