// <auto-generated />
using System;
using Com.RePower.Ocv.Model.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Com.RePower.Ocv.Model.Migrations
{
    [DbContext(typeof(OcvSettingDbContext))]
    [Migration("20230105041335_AddOcvCacheValue")]
    partial class AddOcvCacheValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Com.RePower.Ocv.Model.Dto.OcvCacheValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReserveText1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReserveText2")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReserveText3")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReserveTime1")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReserveTime2")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReserveTime3")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CacheValues");
                });

            modelBuilder.Entity("Com.RePower.Ocv.Model.Dto.OcvSettingItemDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SettingItems");
                });
#pragma warning restore 612, 618
        }
    }
}
